version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3.12.4-alpine
    restart: always
    env_file:
      .env
  
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      .env      
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data:cache

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./wait-for-it.sh -t 20 rabbitmq:5672 -- uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./src:/app:rw
    env_file:
      .env
    ports:
      - '8080:80'
    depends_on:
      - postgres
      - rabbitmq
